name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
      - develop
      - lab_01
  pull_request:
    branches:
      - master
      - develop

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install the necessary packages
        run: pip3.10 install -r requirements.txt

      - name: Run unit tests
        uses: fylein/python-pytest-github-action@v2
        with:
          args: cd app && pytest -vs unit_tests/person.py
