name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
      - develop
      - lab_01
  pull_request:
    branches:
      - master
      - develop

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up python 3.10.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.13'
      
      - name: Run unit tests
        run: make run-tests
